name: 'Tag Commit'
description: 'Tag the current commit'
inputs:
  github_token:
    description: 'Required for permission to tag the repo'
    required: true
runs:
  using: "composite"
  steps:
    - name: Retrieve version from poetry
      shell: bash
      run: |
        PKG_VERSION=$(poetry version --short)
        echo "VERSION=$PKG_VERSION" >> $GITHUB_ENV

    - name: Tag commit using retrieved version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ inputs.github_token }}
        custom_tag: ${{ env.VERSION }}
